name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  owasp_zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web applications (OWASP ZAP)
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@master
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
