name: Run SonarQube with Maven

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up JDK 17
      uses: actions/setup-java@master
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Run Sonar Scan
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=ajobayer_github-devsecops-java-pipeline -Dsonar.organization=ajobayer -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
